name: Kernel Checkers
on:
  workflow_call:
    inputs:
      check_name:
        required: true
        type: string
      base_branch:
        required: false
        type: string
        default: qcom-next-staging
      pr_number:
        type: string
        required: false
      topic_repo:
        type: string
        required: false

jobs:
  checker:
    runs-on:
      group: GHA-Kernel-SelfHosted-RG
      labels: [self-hosted, kernel-prd-u2404-x64-large-od-ephem]

    steps:
      - name: Pull docker image
        uses: qualcomm-linux/kernel-config/.github/actions/pull_docker_image@main
        with:
          image: ${{ vars.TECH_TEAM_NAMESPACE }}/kmake-image:${{ vars.KMAKE_IMAGE_VERSION }}
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Checkout code
        id: sync
        uses: qualcomm-linux/kernel-checkers/.github/actions/sync@main
        with:
          base_branch: ${{ inputs.base_branch }}
          pr_number: ${{ inputs.pr_number }}
          topic_repo: ${{ inputs.topic_repo }}

      - name: Clone kernel-checkers
        run: cd .. && git clone https://github.com/qualcomm-linux/kernel-checkers.git

      - name: Run kernel check
        run: |
          bash ../kernel-checkers/${{ inputs.check_name }}.sh --kernel-src ${{ steps.sync.outputs.kernel_src }} \
          --base ${{ steps.sync.outputs.base_sha }} --head ${{ steps.sync.outputs.head_sha }}
